### ISSUE TITLE
Form Refinements

### ISSUE THREAD

**Issue by siqbal181** [Pensano-dev/meal-plan-generator#6]
Form is created at a very basic level but could do with some refinements such as: 
- Edge cases for form inputs EG:
- User can't submit form without checking some boxes
- User inputs "other" fields without commas
- Anything else which ensures the user inputs the details exactly as we need

**Comment by junocchi** [comment]
- changed checkboxes to radio for the mandatory age options
- changed for= to htmlFor= (The reason is that in JSX, for is a reserved keyword for "for loops." To avoid conflicts, JSX uses htmlFor to achieve the same behavior as the regular for attribute in HTML.)
