### ISSUE TITLE
CSS For Meal Plan Form

### ISSUE THREAD

**Issue by siqbal181** [Pensano-dev/meal-plan-generator#7]

**Comment by siqbal181** [comment]
- Add classnames to the form 
- Div out the forms into blocks
- CSS stylings

**Comment by junocchi** [comment]
I pushed the changes to my branch called "FormOptions".

**Comment by junocchi** [comment]
For reference, this is where I got the React-allergens icons from: https://github.com/dsanchez07/react-allergens/tree/master

**Comment by pablisch** [comment]
Although there may be changes, I believe this is done.
